name: Python application

on:
  workflow_dispatch:
    inputs:
      onefile:
        description: "File to be built"
        default: mlLevel

jobs:
  setup-params:
    runs-on: ubuntu-latest
    outputs:
      onefile: ${{ steps.params.outputs.onefile }}
    steps:
    - name: Set up parameters
      id: params
      run: |
        echo "onefile=${{ inputs.onefile || 'mlLevel' }}" >> $GITHUB_OUTPUT

  build:
    needs: setup-params
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        repository: 'Roman-inc/nunet'
        token: ${{ secrets.GIT_TOKEN }}
        fetch-depth: 0
        ref: main
    - name: Set up Python 3.10
      uses: actions/setup-python@v5.6.0
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build app
      run: |
        pyinstaller --onefile ${{ needs.setup-params.outputs.onefile }}.py

    - name: Upload app to artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ needs.setup-params.outputs.onefile }}-${{ matrix.os }}
        path: dist/
