name: Scan repos and build

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    env:
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v5.6.0
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pwd
          ps -lah
          python -m pip install --upgrade pip
          pip install -r .github/scripts/requirements.txt

      - name: Run Scanner
        run:
          python .github/scripts/scan_repos.py
      